### ISSUE TITLE
npm install results in errors

### ISSUE THREAD

**Issue by sdellis** [mzarillopu/ds-storybook-6x#1]
I've tried `npm install` using multiple versions of Node v12.* and I get the same error: 

```
ERROR in ./src/index.ts
Module not found: Error: Can't resolve './components' in '/Users/elliss/Development/ds-storybook-6x/src'
 @ ./src/index.ts 11:0-29 11:0-29
```

**Comment by mzarillopu** [comment]
I am getting the same thing when I run a fresh install.  You should be able to proceed even though you got that error message.

I will have to look into why it is attempting to run one of the builds during the “npm install” command.  There must be some post install hook or something.

Any idea why that might be happening?

**Comment by mzarillopu** [comment]
The npm install problem should be resolved now.  There was a “prepublish” script in the scripts section that was executing automatically during the “npm install” command execution.

I have removed that command and now it installs without error.

**Comment by sdellis** [comment]
Works for me now too! Thanks. 👍
