### ISSUE TITLE
Stylesheets don't load in dev server due to unsupported MIME types

### ISSUE THREAD

**Issue by sdellis** [mzarillopu/ds-storybook-6x#2]
![Screen Shot 2020-10-29 at 5 08 34 PM](https://user-images.githubusercontent.com/609368/97632946-ac23fe80-1a09-11eb-9ed3-1b21479fbe21.png)

**Comment by mzarillopu** [comment]
I am not getting this one, even with a fresh install.

Can you provide any additional details?  Do you run into this problem right away or have you modified some of the sources?  What happens if you refresh the page?
